from os import getenv

CLIENT_APP_ADDRESS_HTTP = getenv("CLIENT_APP_ADDRESS_HTTP", "http://localhost:5173")
CLIENT_APP_ADDRESS_HTTPS = getenv("CLIENT_APP_ADDRESS_HTTPS", "https://localhost:5173")
CORS_ALLOWED_ORIGINS = [CLIENT_APP_ADDRESS_HTTP, CLIENT_APP_ADDRESS_HTTPS]
