# Generated by Django 5.1.5 on 2025-01-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Education', 'Education'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Transfer', 'Transfer'), ('Bill', 'Bill'), ('Subscription', 'Subscription'), ('Other', 'Other'), ('Not Identified', 'Not Identified')], default='Not Identified', max_length=255, null=True),
        ),
    ]
